<?php

namespace Database\Seeders;

use App\Models\Domain;
use App\Models\EvaluationItem;
use Illuminate\Database\Seeder;

class InitialGradesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            'Inicial 1' => [
                'RELACIONES CON EL MEDIO NATURAL Y CULTURAL' => [
                    'Identificar a los seres vivos de su entorno a través de la exploración del mundo natural.',
                    'Reconocer y diferenciar entre elementos naturales y artificiales por medio de los sentidos.',
                    'Reconocer diferentes elementos de su entorno natural mediante la discriminación sensorial.',
                    'Identificar las características de los animales que pueden cumplir el rol de mascota y los cuidados que requieren.',
                    'Reconocer las características de las plantas alimenticias comprendiendo su importancia en la alimentación.',
                    'Identificar los alimentos nutritivos reconociendo la importancia de éstos en su crecimiento.',
                    'Realizar acciones que apoyan al cuidado del medio ambiente como: botar la basura en su lugar, no desperdiciar el agua, entre otras.',
                    'Apoyar en el cuidado de plantas y animales de su entorno.',
                    'Reconocer y apreciar algunas expresiones culturales importantes de su localidad.',
                    'Participar en algunas prácticas tradicionales de su entorno disfrutando de las diferentes manifestaciones culturales.',
                ],
                'EXPRESIÓN ARTÍSTICA' => [
                    'Representar a personas de su entorno asumiendo roles a través del juego simbólico.',
                    'Integrarse durante la ejecución de rondas, bailes y juegos tradicionales.',
                    'Imitar pasos de baile intentando reproducir los movimientos y seguir el ritmo.',
                    'Cantar canciones cortas asociando la letra con expresiones de su cuerpo.',
                    'Experimentar a través de la manipulación de materiales y mezcla de colores la realización de trabajos creativos.',
                    'Expresar sus vivencias y experiencias a través del dibujo libre.',
                    'Expresar su gusto o disgusto al observar una obra artística.',
                    'Ejecutar patrones de ritmos con partes del cuerpo o instrumentos.',
                    'Imitar e identificar sonidos del entorno.',
                ],
                'RELACIONES LÓGICO MATEMÁTICAS' => [
                    'Ordenar en secuencias lógicas sucesos de hasta tres eventos.',
                    'Identificar características del día y la noche.',
                    'Identificar nociones de tiempo (antes y ahora).',
                    'Reconocer la ubicación de objetos (arriba/abajo, dentro/fuera, cerca/lejos).',
                    'Identificar nociones de medida (alto/bajo, pesado/liviano).',
                    'Identificar formas en objetos del entorno.',
                    'Reconocer figuras geométricas básicas.',
                    'Reconocer colores primarios, blanco y negro.',
                    'Contar oralmente del 1 al 10.',
                    'Comprender la relación número-cantidad hasta el 5.',
                    'Clasificar objetos por atributos.',
                    'Diferenciar más y menos.',
                    'Comparar tamaños.',
                    'Imitar patrones simples.',
                ],
                'COMPRENSIÓN Y EXPRESIÓN DEL LENGUAJE' => [
                    'Comunicarse utilizando vocabulario básico.',
                    'Participar en conversaciones cortas.',
                    'Describir imágenes oralmente.',
                    'Reproducir canciones y poemas.',
                    'Expresarse con oraciones simples.',
                    'Seguir instrucciones sencillas.',
                    'Relatar cuentos con apoyo.',
                    'Responder preguntas sobre textos.',
                    'Identificar etiquetas y rótulos.',
                    'Contar cuentos a partir de imágenes.',
                    'Identificar su cuento preferido.',
                    'Realizar movimientos articulatorios.',
                    'Expresarse oralmente de manera comprensible.',
                ],
                'CONVIVENCIA' => [
                    'Integrarse en juegos grupales.',
                    'Establecer relaciones con su entorno familiar y escolar.',
                    'Relacionarse sin discriminación.',
                    'Desarrollar vínculos de amistad.',
                    'Colaborar con adultos en actividades sencillas.',
                    'Mostrar interés por problemas de otros.',
                    'Reconocer emociones de los demás.',
                    'Identificar miembros de su familia y roles.',
                    'Reconocer oficios de la comunidad.',
                    'Practicar normas de convivencia.',
                ],
                'EXPRESIÓN CORPORAL' => [
                    'Caminar y correr manteniendo el equilibrio.',
                    'Saltar en diferentes formas.',
                    'Subir y bajar escaleras.',
                    'Trepar y reptar.',
                    'Galopar y salticar.',
                    'Coordinar desplazamientos.',
                    'Controlar fuerza al lanzar, atrapar y patear.',
                    'Realizar ejercicios de equilibrio.',
                    'Mantener control postural.',
                    'Ejecutar movimientos segmentados.',
                ],
                'IDENTIDAD Y AUTONOMÍA' => [
                    'Comunicar datos personales.',
                    'Identificar diferencias entre niños y niñas.',
                    'Reconocer características físicas propias.',
                    'Expresar emociones y sentimientos.',
                    'Elegir según gustos y preferencias.',
                    'Reconocerse como parte de una familia.',
                    'Practicar hábitos de higiene.',
                    'Usar el baño con autonomía parcial.',
                    'Vestirse parcialmente sin ayuda.',
                    'Utilizar utensilios al alimentarse.',
                    'Mantener el orden.',
                    'Identificar situaciones de peligro.',
                    'Actuar ante situaciones de riesgo.',
                    'Aplicar normas de seguridad.',
                ],
            ],
            'Inicial 2' => [
                'IDENTIDAD Y AUTONOMÍA' => [
                    'Comunicar algunos datos de su identidad como: nombres completos, edad, nombres de familiares cercanos, lugar dónde vive.',
                    'Demostrar curiosidad por las características físicas (genitales) que le permiten reconocerse como niño y niña.',
                    'Identificar la importancia de usar el cinturón de seguridad para promover el autocuidado y la protección personal.',
                    'Identificar las situaciones de peligro a las que se puede exponer en su entorno inmediato y seguir pautas para evitarlas.',
                    'Identificar sus características físicas y las de las personas de su entorno.',
                    'Identificar y manifestar sus emociones y sentimientos expresando sus causas.',
                    'Identificarse como miembro de una familia reconociéndose como parte importante de la misma.',
                    'Practicar con autonomía hábitos de higiene personal.',
                    'Practicar hábitos de orden ubicando los objetos en su lugar.',
                    'Practicar acciones en situaciones de riesgo (temblores, incendios, etc.).',
                    'Practicar normas de seguridad para evitar accidentes.',
                    'Realizar normas de aseo de manera independiente al ir al baño.',
                    'Reconocer la importancia del uso del casco y protección.',
                    'Resolver situaciones problemáticas de forma creativa y autónoma.',
                    'Seleccionar prendas de vestir según el clima.',
                    'Tomar decisiones según gustos y preferencias.',
                    'Utilizar cuchara, tenedor y vaso de forma autónoma.',
                    'Vestirse y desvestirse de manera independiente.',
                ],
                'CONVIVENCIA' => [
                    'Apoyar y motivar a otros en actividades grupales.',
                    'Asumir y respetar normas de convivencia.',
                    'Colaborar con otros niños y adultos.',
                    'Demostrar solidaridad.',
                    'Mostrar respeto hacia actores viales.',
                    'Demostrar preferencia por jugar con un amigo.',
                    'Demostrar sensibilidad ante emociones de otros.',
                    'Desarrollar la capacidad de esperar.',
                    'Identificar instituciones y profesiones.',
                    'Identificar profesiones de su familia.',
                    'Incrementar su interacción social.',
                    'Observar emociones en otros.',
                    'Participar en juegos grupales con reglas.',
                    'Practicar el ahorro.',
                    'Respetar diferencias individuales.',
                ],
                'RELACIONES CON EL MEDIO NATURAL Y CULTURAL' => [
                    'Comunicar preferencias y desacuerdos de forma asertiva.',
                    'Construir conexiones emocionales con su entorno.',
                    'Identificar oportunidades para cuidar recursos.',
                    'Diferenciar alimentos nutritivos y no nutritivos.',
                    'Diferenciar pertenencias.',
                    'Diferenciar seres vivos y no vivos.',
                    'Comparar elementos del entorno.',
                    'Explorar fenómenos naturales.',
                    'Identificar características de plantas.',
                    'Identificar animales domésticos y silvestres.',
                    'Identificar características del mar.',
                    'Reconocer prácticas socioculturales.',
                    'Observar el ciclo de vida de plantas.',
                    'Participar en prácticas de cuidado del planeta.',
                    'Participar en prácticas culturales.',
                    'Practicar cuidado ambiental.',
                    'Proteger plantas y animales.',
                    'Reconocer uso del dinero.',
                    'Reconocer consecuencias de no cuidar pertenencias.',
                    'Reconocer transporte sostenible.',
                ],
                'RELACIONES LÓGICAS MATEMÁTICAS' => [
                    'Asociar formas con figuras geométricas.',
                    'Clasificar objetos con dos atributos.',
                    'Comparar colecciones (más, igual, menos).',
                    'Ordenar objetos por tamaño.',
                    'Comprender número-cantidad hasta el 10.',
                    'Relacionar numeral con cantidad hasta el 5.',
                    'Contar del 1 al 15.',
                    'Reproducir patrones.',
                    'Establecer correspondencias.',
                    'Identificar mañana, tarde y noche.',
                    'Identificar medidas (largo/corto, grueso/delgado).',
                    'Reconocer figuras geométricas básicas.',
                    'Diferenciar deseos y necesidades.',
                    'Identificar nociones de tiempo.',
                    'Reconocer números de emergencia.',
                    'Identificar semejanzas y diferencias.',
                    'Ordenar secuencias de eventos.',
                    'Reconocer dinero.',
                    'Ubicar objetos en el espacio.',
                    'Reconocer colores secundarios.',
                    'Comparar características personales.',
                    'Relacionar trabajo y dinero.',
                ],
                'COMPRENSIÓN Y EXPRESIÓN DEL LENGUAJE' => [
                    'Asociar portada con título de cuentos.',
                    'Colaborar en textos colectivos.',
                    'Comprender el derecho a decir no.',
                    'Comunicarse mediante dibujos.',
                    'Ampliar vocabulario.',
                    'Contar cuentos siguiendo secuencia.',
                    'Describir imágenes.',
                    'Expresarse oralmente correctamente.',
                    'Usar oraciones completas.',
                    'Identificar sonidos iniciales.',
                    'Identificar adulto de confianza.',
                    'Participar en conversaciones largas.',
                    'Producir rimas.',
                    'Modificar cuentos.',
                    'Realizar movimientos articulatorios.',
                    'Reconocer etiquetas.',
                    'Relatar cuentos sin apoyo.',
                    'Reproducir trabalenguas y poemas.',
                    'Responder preguntas.',
                    'Seguir instrucciones complejas.',
                ],
                'EXPRESIÓN ARTÍSTICA' => [
                    'Cantar canciones con ritmo.',
                    'Comunicar ideas por escrito (inicio de escritura).',
                    'Ejecutar patrones rítmicos.',
                    'Expresar emociones con arte.',
                    'Opinar sobre obras artísticas.',
                    'Expresar vivencias mediante dibujo.',
                    'Mantener ritmo en coreografías.',
                    'Participar en dramatizaciones.',
                    'Participar en juegos tradicionales.',
                    'Realizar actividades grafo plásticas.',
                ],
                'EXPRESIÓN CORPORAL Y MOTRICIDAD' => [
                    'Caminar y correr con equilibrio.',
                    'Desplazarse con coordinación.',
                    'Discriminar sonidos.',
                    'Ejecutar actividades con control muscular.',
                    'Usar lateralidad dominante.',
                    'Galopar y saltar con coordinación.',
                    'Identificar partes del cuerpo.',
                    'Mantener equilibrio en superficies.',
                    'Mantener control postural.',
                    'Orientarse en el espacio.',
                    'Realizar movimientos combinados.',
                    'Coordinar visomotricidad.',
                    'Ejecutar desplazamientos variados.',
                    'Realizar ejercicios de equilibrio.',
                    'Trabajar simetría corporal.',
                    'Ejecutar movimientos segmentados.',
                    'Coordinar movimientos laterales.',
                    'Coordinar ojo-pie.',
                    'Representar gráficamente.',
                    'Respetar normas de tránsito.',
                    'Representar figura humana.',
                    'Saltar alternando pies.',
                    'Saltar obstáculos.',
                    'Subir y bajar escaleras.',
                    'Trepar y reptar.',
                    'Ubicar partes del cuerpo en el espacio.',
                    'Usar espacio gráfico.',
                    'Utilizar pinza digital.',
                ],
            ],
            'Preparatoria' => [
                'IDENTIDAD Y AUTONOMÍA' => [
                    'Reconoce sus estados corporales y de ánimo, sus posibilidades de interpretación y traducción de mensajes corporales propios. (Ref.I.EF.1.3.2.)',
                    'Reconoce la necesidad de utilizar los cuidados básicos de higiene personal durante su participación en prácticas corporales.',
                ],
                'EL YO: LA IDENTIDAD' => [
                    'Describe con claridad, mediante cuentos cortos, situaciones en las que el uso de transporte alternativo contribuye a la protección del medio ambiente. (I.ECA.1.1.4)',
                    'Manifiesta curiosidad e interés por explorar de manera espontánea las cualidades de la voz, el cuerpo y de elementos del entorno. (Ref. I.ECA.1.1.1.)',
                    'Participa activamente en la realización de juegos sensoriomotores. (Ref. I.ECA.1.1.2.)',
                ],
                'EL ENCUENTRO CON OTROS: LA ALTERIDAD' => [
                    'Hace una diferenciación básica de las manifestaciones culturales y artísticas de su entorno próximo, identificando a sus actores y/o creadores. (Ref. I.ECA.1.2.1.)',
                    'Reconoce y describe corporal, gráfica o verbalmente ideas, sentimientos o emociones en la observación de imágenes. (Ref. I.ECA.1.2.2.)',
                ],
                'CONVIVENCIA' => [
                    'Reconoce que tiene una historia personal, familiar y que forma parte de una comunidad y de un núcleo familiar. (Ref.I.CS.1.1.2.)',
                    'Practica normas de respeto consigo mismo y con los demás, respetando las diferencias individuales existentes. (I.CS.1.3.1.)',
                    'Reconoce sus derechos y responsabilidades y la importancia de asumir con responsabilidad sus compromisos. (I.CS.1.3.2.)',
                ],
                'RELACIÓN LÓGICA-MATEMÁTICA' => [
                    'Describe y reproduce patrones con objetos del entorno por color, forma, tamaño, longitud o con siluetas de figuras geométricas. (I.M.1.1.1.)',
                    'Resuelve situaciones cotidianas que requieren de la comparación de colecciones de objetos mediante el uso de cuantificadores. (I.M.1.2.1.)',
                ],
                'COMPRENSIÓN Y EXPRESIÓN ORAL Y ESCRITA' => [
                    'Interpreta la silueta y los paratextos de diversos textos escritos cotidianos, deduciendo su contenido y uso. (I.LL.1.1.1.)',
                    'Distingue palabras y expresiones coloquiales de su localidad e indaga sobre sus significados. (I.LL.1.2.1.)',
                    'Desarrolla la expresión oral en contextos cotidianos usando la conciencia lingüística. (I.LL.1.3.1.)',
                ],
                'DESCUBRIMIENTO Y COMPRENSIÓN DEL MEDIO NATURAL Y CULTURAL' => [
                    'Infiere algunas de las relaciones de causa-efecto que se establecen en la naturaleza. (I.CN.1.1.1.)',
                    'Diferencia objetos naturales de objetos artificiales del entorno próximo. (I.CN.1.1.2.)',
                ],
                'COMPRENSIÓN Y EXPRESIÓN ARTISTICA' => [
                    'Explora y representa corporal, musical, gráfica o verbalmente ideas, sentimientos o emociones de forma libre y espontánea. (I.ECA.1.1.1.)',
                    'Dramatiza de manera creativa las acciones básicas a seguir en caso de un accidente de tránsito. (I.ECA.1.1.3.)',
                ],
                'EXPRESIÓN CORPORAL' => [
                    'Construye y comunica mensajes (convencionales y/o espontáneos) utilizando diferentes recursos expresivos (gestos, ritmos, posturas). (I.EF.1.1.1.)',
                    'Establece acuerdos colectivos que favorezcan la participación en diferentes prácticas corporales expresivo-comunicativas. (Ref. I.EF.1.1.3.)',
                ],
                'CÍVICA Y ACOMPAÑAMIENTO INTEGRAL EN EL AULA' => [
                    'Autoconocimiento.',
                    'Pensamiento Crítico.',
                    'Manejo de Problemas y Toma de Decisiones.',
                    'Trabajo en Equipo y Conciencia Social.',
                    'Relaciones Interpersonales y Manejo de Conflictos.',
                    'Manejo de Emociones y Sentimientos.',
                ],
            ],
        ];

        foreach ($data as $level => $subjects) {
            foreach ($subjects as $subjectName => $destrezas) {
                $domain = Domain::firstOrCreate([
                    'name' => $subjectName,
                    'level' => $level,
                ]);

                foreach ($destrezas as $index => $destreza) {
                    EvaluationItem::firstOrCreate([
                        'domain_id' => $domain->id,
                        'description' => $destreza,
                    ], [
                        'type' => 'destreza',
                    ]);
                }
            }
        }
    }
}
