<?php

namespace Database\Seeders;

use App\Models\Domain;
use App\Models\EvaluationItem;
use Illuminate\Database\Seeder;

class InitialGradesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            'Inicial 1' => [
                'RELACIONES CON EL MEDIO NATURAL Y CULTURAL' => [
                    'Identificar a los seres vivos de su entorno a través de la exploración del mundo natural.',
                    'Reconocer y diferenciar entre elementos naturales y artificiales por medio de los sentidos.',
                    'Reconocer diferentes elementos de su entorno natural mediante la discriminación sensorial.',
                    'Identificar las características de los animales que pueden cumplir el rol de mascota y los cuidados que requieren.',
                    'Reconocer las características de las plantas alimenticias comprendiendo su importancia en la alimentación.',
                    'Identificar los alimentos nutritivos reconociendo la importancia de éstos en su crecimiento.',
                    'Realizar acciones que apoyan al cuidado del medio ambiente como: botar la basura en su lugar, no desperdiciar el agua, entre otras.',
                    'Apoyar en el cuidado de plantas y animales de su entorno.',
                    'Reconocer y apreciar algunas expresiones culturales importantes de su localidad.',
                    'Participar en algunas prácticas tradicionales de su entorno disfrutando de las diferentes manifestaciones culturales.',
                ],
                'EXPRESIÓN ARTÍSTICA' => [
                    'Representar a personas de su entorno asumiendo roles a través del juego simbólico.',
                    'Integrarse durante la ejecución de rondas, bailes y juegos tradicionales.',
                    'Imitar pasos de baile intentando reproducir los movimientos y seguir el ritmo.',
                    'Cantar canciones cortas asociando la letra con expresiones de su cuerpo.',
                    'Experimentar a través de la manipulación de materiales y mezcla de colores la realización de trabajos creativos.',
                    'Expresar sus vivencias y experiencias a través del dibujo libre.',
                    'Expresar su gusto o disgusto al observar una obra artística.',
                    'Ejecutar patrones de ritmos con partes del cuerpo o instrumentos.',
                    'Imitar e identificar sonidos del entorno.',
                ],
                'RELACIONES LÓGICO MATEMÁTICAS' => [
                    'Ordenar en secuencias lógicas sucesos de hasta tres eventos.',
                    'Identificar características del día y la noche.',
                    'Identificar nociones de tiempo (antes y ahora).',
                    'Reconocer la ubicación de objetos (arriba/abajo, dentro/fuera, cerca/lejos).',
                    'Identificar nociones de medida (alto/bajo, pesado/liviano).',
                    'Identificar formas en objetos del entorno.',
                    'Reconocer figuras geométricas básicas.',
                    'Reconocer colores primarios, blanco y negro.',
                    'Contar oralmente del 1 al 10.',
                    'Comprender la relación número-cantidad hasta el 5.',
                    'Clasificar objetos por atributos.',
                    'Diferenciar más y menos.',
                    'Comparar tamaños.',
                    'Imitar patrones simples.',
                ],
                'COMPRENSIÓN Y EXPRESIÓN DEL LENGUAJE' => [
                    'Comunicarse utilizando vocabulario básico.',
                    'Participar en conversaciones cortas.',
                    'Describir imágenes oralmente.',
                    'Reproducir canciones y poemas.',
                    'Expresarse con oraciones simples.',
                    'Seguir instrucciones sencillas.',
                    'Relatar cuentos con apoyo.',
                    'Responder preguntas sobre textos.',
                    'Identificar etiquetas y rótulos.',
                    'Contar cuentos a partir de imágenes.',
                    'Identificar su cuento preferido.',
                    'Realizar movimientos articulatorios.',
                    'Expresarse oralmente de manera comprensible.',
                ],
                'CONVIVENCIA' => [
                    'Integrarse en juegos grupales.',
                    'Establecer relaciones con su entorno familiar y escolar.',
                    'Relacionarse sin discriminación.',
                    'Desarrollar vínculos de amistad.',
                    'Colaborar con adultos en actividades sencillas.',
                    'Mostrar interés por problemas de otros.',
                    'Reconocer emociones de los demás.',
                    'Identificar miembros de su familia y roles.',
                    'Reconocer oficios de la comunidad.',
                    'Practicar normas de convivencia.',
                ],
                'EXPRESIÓN CORPORAL' => [
                    'Caminar y correr manteniendo el equilibrio.',
                    'Saltar en diferentes formas.',
                    'Subir y bajar escaleras.',
                    'Trepar y reptar.',
                    'Galopar y salticar.',
                    'Coordinar desplazamientos.',
                    'Controlar fuerza al lanzar, atrapar y patear.',
                    'Realizar ejercicios de equilibrio.',
                    'Mantener control postural.',
                    'Ejecutar movimientos segmentados.',
                ],
                'IDENTIDAD Y AUTONOMÍA' => [
                    'Comunicar datos personales.',
                    'Identificar diferencias entre niños y niñas.',
                    'Reconocer características físicas propias.',
                    'Expresar emociones y sentimientos.',
                    'Elegir según gustos y preferencias.',
                    'Reconocerse como parte de una familia.',
                    'Practicar hábitos de higiene.',
                    'Usar el baño con autonomía parcial.',
                    'Vestirse parcialmente sin ayuda.',
                    'Utilizar utensilios al alimentarse.',
                    'Mantener el orden.',
                    'Identificar situaciones de peligro.',
                    'Actuar ante situaciones de riesgo.',
                    'Aplicar normas de seguridad.',
                ],
            ],
            'Inicial 2' => [
                'IDENTIDAD Y AUTONOMÍA' => [
                    'Comunicar algunos datos de su identidad como: nombres completos, edad, nombres de familiares cercanos, lugar dónde vive.',
                    'Demostrar curiosidad por las características físicas (genitales) que le permiten reconocerse como niño y niña.',
                    'Identificar la importancia de usar el cinturón de seguridad para promover el autocuidado y la protección personal.',
                    'Identificar las situaciones de peligro a las que se puede exponer en su entorno inmediato y seguir pautas para evitarlas.',
                    'Identificar sus características físicas y las de las personas de su entorno.',
                    'Identificar y manifestar sus emociones y sentimientos expresando sus causas.',
                    'Identificarse como miembro de una familia reconociéndose como parte importante de la misma.',
                    'Practicar con autonomía hábitos de higiene personal.',
                    'Practicar hábitos de orden ubicando los objetos en su lugar.',
                    'Practicar acciones en situaciones de riesgo (temblores, incendios, etc.).',
                    'Practicar normas de seguridad para evitar accidentes.',
                    'Realizar normas de aseo de manera independiente al ir al baño.',
                    'Reconocer la importancia del uso del casco y protección.',
                    'Resolver situaciones problemáticas de forma creativa y autónoma.',
                    'Seleccionar prendas de vestir según el clima.',
                    'Tomar decisiones según gustos y preferencias.',
                    'Utilizar cuchara, tenedor y vaso de forma autónoma.',
                    'Vestirse y desvestirse de manera independiente.',
                ],
                'CONVIVENCIA' => [
                    'Apoyar y motivar a otros en actividades grupales.',
                    'Asumir y respetar normas de convivencia.',
                    'Colaborar con otros niños y adultos.',
                    'Demostrar solidaridad.',
                    'Mostrar respeto hacia actores viales.',
                    'Demostrar preferencia por jugar con un amigo.',
                    'Demostrar sensibilidad ante emociones de otros.',
                    'Desarrollar la capacidad de esperar.',
                    'Identificar instituciones y profesiones.',
                    'Identificar profesiones de su familia.',
                    'Incrementar su interacción social.',
                    'Observar emociones en otros.',
                    'Participar en juegos grupales con reglas.',
                    'Practicar el ahorro.',
                    'Respetar diferencias individuales.',
                ],
                'RELACIONES CON EL MEDIO NATURAL Y CULTURAL' => [
                    'Comunicar preferencias y desacuerdos de forma asertiva.',
                    'Construir conexiones emocionales con su entorno.',
                    'Identificar oportunidades para cuidar recursos.',
                    'Diferenciar alimentos nutritivos y no nutritivos.',
                    'Diferenciar pertenencias.',
                    'Diferenciar seres vivos y no vivos.',
                    'Comparar elementos del entorno.',
                    'Explorar fenómenos naturales.',
                    'Identificar características de plantas.',
                    'Identificar animales domésticos y silvestres.',
                    'Identificar características del mar.',
                    'Reconocer prácticas socioculturales.',
                    'Observar el ciclo de vida de plantas.',
                    'Participar en prácticas de cuidado del planeta.',
                    'Participar en prácticas culturales.',
                    'Practicar cuidado ambiental.',
                    'Proteger plantas y animales.',
                    'Reconocer uso del dinero.',
                    'Reconocer consecuencias de no cuidar pertenencias.',
                    'Reconocer transporte sostenible.',
                ],
                'RELACIONES LÓGICAS MATEMÁTICAS' => [
                    'Asociar formas con figuras geométricas.',
                    'Clasificar objetos con dos atributos.',
                    'Comparar colecciones (más, igual, menos).',
                    'Ordenar objetos por tamaño.',
                    'Comprender número-cantidad hasta el 10.',
                    'Relacionar numeral con cantidad hasta el 5.',
                    'Contar del 1 al 15.',
                    'Reproducir patrones.',
                    'Establecer correspondencias.',
                    'Identificar mañana, tarde y noche.',
                    'Identificar medidas (largo/corto, grueso/delgado).',
                    'Reconocer figuras geométricas básicas.',
                    'Diferenciar deseos y necesidades.',
                    'Identificar nociones de tiempo.',
                    'Reconocer números de emergencia.',
                    'Identificar semejanzas y diferencias.',
                    'Ordenar secuencias de eventos.',
                    'Reconocer dinero.',
                    'Ubicar objetos en el espacio.',
                    'Reconocer colores secundarios.',
                    'Comparar características personales.',
                    'Relacionar trabajo y dinero.',
                ],
                'COMPRENSIÓN Y EXPRESIÓN DEL LENGUAJE' => [
                    'Asociar portada con título de cuentos.',
                    'Colaborar en textos colectivos.',
                    'Comprender el derecho a decir no.',
                    'Comunicarse mediante dibujos.',
                    'Ampliar vocabulario.',
                    'Contar cuentos siguiendo secuencia.',
                    'Describir imágenes.',
                    'Expresarse oralmente correctamente.',
                    'Usar oraciones completas.',
                    'Identificar sonidos iniciales.',
                    'Identificar adulto de confianza.',
                    'Participar en conversaciones largas.',
                    'Producir rimas.',
                    'Modificar cuentos.',
                    'Realizar movimientos articulatorios.',
                    'Reconocer etiquetas.',
                    'Relatar cuentos sin apoyo.',
                    'Reproducir trabalenguas y poemas.',
                    'Responder preguntas.',
                    'Seguir instrucciones complejas.',
                ],
                'EXPRESIÓN ARTÍSTICA' => [
                    'Cantar canciones con ritmo.',
                    'Comunicar ideas por escrito (inicio de escritura).',
                    'Ejecutar patrones rítmicos.',
                    'Expresar emociones con arte.',
                    'Opinar sobre obras artísticas.',
                    'Expresar vivencias mediante dibujo.',
                    'Mantener ritmo en coreografías.',
                    'Participar en dramatizaciones.',
                    'Participar en juegos tradicionales.',
                    'Realizar actividades grafo plásticas.',
                ],
                'EXPRESIÓN CORPORAL Y MOTRICIDAD' => [
                    'Caminar y correr con equilibrio.',
                    'Desplazarse con coordinación.',
                    'Discriminar sonidos.',
                    'Ejecutar actividades con control muscular.',
                    'Usar lateralidad dominante.',
                    'Galopar y saltar con coordinación.',
                    'Identificar partes del cuerpo.',
                    'Mantener equilibrio en superficies.',
                    'Mantener control postural.',
                    'Orientarse en el espacio.',
                    'Realizar movimientos combinados.',
                    'Coordinar visomotricidad.',
                    'Ejecutar desplazamientos variados.',
                    'Realizar ejercicios de equilibrio.',
                    'Trabajar simetría corporal.',
                    'Ejecutar movimientos segmentados.',
                    'Coordinar movimientos laterales.',
                    'Coordinar ojo-pie.',
                    'Representar gráficamente.',
                    'Respetar normas de tránsito.',
                    'Representar figura humana.',
                    'Saltar alternando pies.',
                    'Saltar obstáculos.',
                    'Subir y bajar escaleras.',
                    'Trepar y reptar.',
                    'Ubicar partes del cuerpo en el espacio.',
                    'Usar espacio gráfico.',
                    'Utilizar pinza digital.',
                ],
            ],
            'Preparatoria' => [
                'IDENTIDAD Y AUTONOMÍA' => [
                    'Relaciona las partes principales de su cuerpo y los órganos de los sentidos con su función y percepciones del mundo que lo rodean.',
                    'Promueve hábitos (higiene corporal, alimentación sana, juego y descanso) y medidas preventivas para una vida saludable.',
                    'Expresa sus datos personales (nombre, apellidos, edad, teléfono, lugar donde vive y país en el que vive) y reconoce que es un ser que siente, piensa, opina y tiene necesidades.',
                    'Practica con autonomía y responsabilidad actividades y tareas cotidianas, como hábitos de alimentación, higiene y cuidado personal.',
                    'Reconoce las situaciones de peligro de su entorno cercano para evitar accidentes mediante normas de seguridad y autorregulación.',
                    'Describe los beneficios del uso del casco y otras medidas de protección para su seguridad.',
                    'Comprende palabras familiares e instrucciones simples en inglés relacionadas con su entorno.',
                    'Reconoce que tiene una historia personal, familiar y que forma parte de una comunidad.',
                ],
                'CONVIVENCIA' => [
                    'Practica normas de respeto consigo mismo y con los demás, valorando las diferencias y acuerdos del grupo.',
                    'Reconoce sus derechos y responsabilidades, diferenciando comportamientos positivos y negativos.',
                    'Expresa los beneficios del intercambio (trueque).',
                    'Identifica lugares seguros para comprar en su comunidad.',
                    'Reconoce la organización de la vivienda y la escuela y el uso de la tecnología en estos espacios.',
                    'Identifica la función de los servicios básicos en su localidad.',
                ],
                'DESCUBRIMIENTO Y COMPRENSIÓN DEL MEDIO NATURAL Y CULTURAL' => [
                    'Identifica características, necesidades e importancia de los seres vivos.',
                    'Diferencia seres vivos de objetos inertes.',
                    'Reconoce la importancia de plantas y animales.',
                    'Identifica plantas y animales (domésticos y silvestres).',
                    'Practica el respeto y cuidado del entorno natural.',
                    'Promueve hábitos saludables.',
                    'Explica la importancia de los órganos de los sentidos.',
                    'Reconoce alimentos de su localidad.',
                    'Identifica propiedades físicas de la materia.',
                    'Clasifica materiales naturales y artificiales.',
                    'Relaciona movimiento con la fuerza (halar y empujar).',
                    'Describe cambios en materiales por acción de agentes naturales.',
                    'Identifica fuentes de luz y sonido.',
                    'Explica características del entorno natural y del clima.',
                    'Reconoce medios de transporte, comunicación y profesiones.',
                    'Identifica manifestaciones culturales de su localidad.',
                ],
                'RELACIÓN LÓGICO-MATEMÁTICA' => [
                    'Resuelve problemas organizando datos de situaciones cotidianas.',
                    'Compara objetos según características (color, tamaño, forma, etc.).',
                    'Describe ubicación de objetos.',
                    'Construye series y patrones.',
                    'Clasifica medios de transporte según contaminación.',
                    'Ordena secuencias numéricas del 1 al 10 y ordinales.',
                    'Resuelve problemas con suma, resta y conteo hasta 20.',
                    'Identifica figuras geométricas en su entorno.',
                    'Clasifica objetos según diferentes magnitudes.',
                    'Usa medidas no convencionales.',
                    'Organiza secuencias de tiempo.',
                    'Reconoce uso responsable del dinero, gasto y ahorro.',
                ],
                'COMPRENSIÓN Y EXPRESIÓN ORAL Y ESCRITA' => [
                    'Sigue instrucciones simples en inglés.',
                    'Usa expresiones de cortesía (please, thank you).',
                    'Interpreta textos y paratextos.',
                    'Reconoce expresiones propias de su localidad.',
                    'Desarrolla la expresión oral en contextos cotidianos.',
                    'Comenta experiencias familiares.',
                    'Comprende textos relacionándolos con experiencias previas.',
                    'Lee por placer y registra información.',
                    'Expresa ideas mediante escritura inicial.',
                    'Disfruta la escucha de textos literarios y los representa.',
                ],
                'COMPRENSIÓN Y EXPRESIÓN ARTÍSTICA' => [
                    'Expresa ideas y emociones de forma libre (corporal, musical, gráfica).',
                    'Experimenta con sus sentidos para expresarse.',
                    'Dramatiza acciones relacionadas con la seguridad.',
                ],
                'EXPRESIÓN CORPORAL' => [
                    'Construye y comunica mensajes mediante el cuerpo.',
                    'Establece acuerdos para la participación en actividades corporales.',
                    'Utiliza gestos, ritmos y movimientos para expresarse.',
                ],
                'PRÁCTICAS LÚDICAS' => [
                    'Respeta reglas, roles y acuerdos en juegos.',
                    'Ajusta sus movimientos según el juego y su estado corporal.',
                ],
                'PRÁCTICAS GIMNÁSTICAS' => [
                    'Experimenta habilidades motrices y reconoce factores que influyen en su práctica.',
                ],
                'PRÁCTICAS CORPORALES EXPRESIVAS' => [
                    'Comunica mensajes mediante el cuerpo.',
                    'Reconoce sus estados corporales y emocionales.',
                ],
                'CONSTRUCCIÓN DE LA IDENTIDAD CULTURAL' => [
                    'Participa en actividades corporales reconociendo su cuerpo y movimientos.',
                ],
                'RELACIÓN ENTRE PRÁCTICAS CORPORALES Y SALUD' => [
                    'Establece acuerdos para el cuidado personal y colectivo.',
                    'Reconoce la importancia de la higiene personal.',
                ],
                'EL YO: LA IDENTIDAD' => [
                    'Expresa ideas sobre el cuidado del ambiente (ej. transporte alternativo).',
                    'Muestra curiosidad por explorar su entorno.',
                    'Participa en juegos sensoriomotores.',
                ],
                'EL ENCUENTRO CON OTROS (ALTERIDAD)' => [
                    'Reconoce manifestaciones culturales y artísticas.',
                    'Expresa emociones a partir de la observación.',
                ],
                'EL ENTORNO: ESPACIO, TIEMPO Y OBJETOS' => [
                    'Establece relaciones empáticas en actividades colectivas.',
                    'Participa en procesos de creación artística grupal.',
                ],
                'CÍVICA Y ACOMPAÑAMIENTO INTEGRAL' => [
                    'Autoconocimiento',
                    'Pensamiento crítico',
                    'Manejo de problemas',
                    'Toma de decisiones',
                    'Trabajo en equipo',
                    'Conciencia social',
                    'Relaciones interpersonales',
                    'Manejo de conflictos',
                    'Manejo de emociones y sentimientos',
                ],
            ],
        ];

        foreach ($data as $level => $subjects) {
            foreach ($subjects as $subjectName => $destrezas) {
                $domain = Domain::firstOrCreate([
                    'name' => $subjectName,
                    'level' => $level,
                ]);

                foreach ($destrezas as $index => $destreza) {
                    EvaluationItem::firstOrCreate([
                        'domain_id' => $domain->id,
                        'description' => $destreza,
                    ], [
                        'type' => 'destreza',
                    ]);
                }
            }
        }
    }
}
